#
# Comments...
#

FROM golang:1.16 AS builder

WORKDIR ./src/github.com/dmw2151/out_indexed_log

COPY ./ ./

# Build Indexed File Plugin
RUN cd ./cmd/plugins &&\ 
    env CGO_ENABLED=1 go build -buildmode=c-shared \
        -o /plugins/idx/plugin.so \
        ./main.go

# Create a builder container – ~900MB vs. ~130MB
FROM fluent/fluent-bit:1.8.12

COPY --from=builder /plugins /plugins
